on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Build

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build-std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        FEATURES: ['', 'from_str', 'std', 'serde']

        include:
          # Test nightly but don't fail
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=x86_64-unknown-linux-gnu --features=${{ matrix.FEATURES }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=x86_64-unknown-linux-gnu --features=${{ matrix.FEATURES }}

  build-no-std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET: [thumbv6m-none-eabi, thumbv7m-none-eabi]

        include:
          # Test nightly but don't fail
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ['', 'from_str', 'std']
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.52.1 # clippy is too much of a moving target at the moment
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features=${{ matrix.FEATURES }}
