on:
  push:
    branches: [staging, trying, main]
  pull_request:

name: Build

env:
  RUSTFLAGS: "--deny warnings"
  MSRV: 1.76

jobs:
  build-std-msrv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ["", "from_str", "std", "serde"]
        TARGET: ["x86_64-unknown-linux-gnu"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
          target: ${{ matrix.TARGET }}
      - name: Build std
        run: cargo build --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}
      - name: Test std
        run: cargo test --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}

  build-no-std-msrv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ["", "from_str"]
        TARGET: [thumbv6m-none-eabi, thumbv7m-none-eabi]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
          target: ${{ matrix.TARGET }}
      - name: Build std
        run: cargo build --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}

  build-std-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ["", "from_str", "std", "serde"]
        TARGET: ["x86_64-unknown-linux-gnu"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.TARGET }}
      - name: Build std
        run: cargo build --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}
      - name: Test std
        run: cargo test --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}

  build-no-std-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ["", "from_str"]
        TARGET: [thumbv6m-none-eabi, thumbv7m-none-eabi]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.TARGET }}
      - name: Build std
        run: cargo build --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}

  build-std-nightly:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: ["x86_64-unknown-linux-gnu"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: ${{ matrix.TARGET }}
      - name: Build std
        run: cargo build --target=${{ matrix.TARGET }} --all-features
      - name: Test std
        run: cargo test --target=${{ matrix.TARGET }} --all-features

  build-no-std-nightly:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ["from_str"]
        TARGET: [thumbv7m-none-eabi]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: ${{ matrix.TARGET }}
      - name: Build std
        run: cargo build --target=${{ matrix.TARGET }} --features=${{ matrix.FEATURES }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
          components: rustfmt
      - name: Format
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURES: ["", "from_str", "std", "serde"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.MSRV }}
          components: clippy
      - name: Clippy
        run: cargo clippy --features=${{ matrix.FEATURES }} -- -D warnings
